spring:
  application:
    name: assisment
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Strictly rely on Flyway migrations
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25 # Optimized for batch session creation
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000


server:
  port: 8080
